// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	Email     interface{} `json:"email"`
	Password  interface{} `json:"password"`
	CreatedAt time.Time   `json:"created_at"`
}
